version: "3.8"

services:
  backend:
    build: ./src
    container_name: backend
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PYTHONPATH: /app
    command: >
      sh -c "alembic -c src/alembic.ini upgrade head &&
         uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"   # фронт будет обращаться к API через этот порт
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  frontend:
     build: ./frontend
     container_name: frontend
     command: npm run dev
     ports:
       - "5173:5173"
     working_dir: /app
     volumes:
       - ./frontend:/app
       - /app/node_modules
     environment:
       CHOKIDAR_USEPOLLING: "true"  # важно для Linux/WSL, чтобы Vite видел изменения
     depends_on:
       - backend

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  postgres_data:
  redis_data: