"""cascade del in invites

Revision ID: 1996e4fa1ad6
Revises: 1662f7242909
Create Date: 2026-04-22 17:15:47.408746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1996e4fa1ad6'
down_revision: Union[str, Sequence[str], None] = '1662f7242909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_invites_project_id_fkey'), 'user_invites', type_='foreignkey')
    op.create_foreign_key(None, 'user_invites', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_invites', type_='foreignkey')
    op.create_foreign_key(op.f('user_invites_project_id_fkey'), 'user_invites', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
