"""comments replies

Revision ID: 6650902c0a58
Revises: 907b773ec0d1
Create Date: 2026-04-14 20:24:21.918741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6650902c0a58'
down_revision: Union[str, Sequence[str], None] = '907b773ec0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_reply_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_reply_deleted')
    # ### end Alembic commands ###
