"""settings

Revision ID: 8a7252c2e517
Revises: 1996e4fa1ad6
Create Date: 2026-04-30 14:52:37.651761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a7252c2e517'
down_revision: Union[str, Sequence[str], None] = '1996e4fa1ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('theme', sa.Enum('light', 'dark', native_enum=False), nullable=False))
    op.add_column('user_settings', sa.Column('theme_color', sa.Enum('green', 'yellow', 'blue', 'red', 'sky', 'orange', 'purple', native_enum=False), nullable=False))
    op.add_column('user_settings', sa.Column('font_size', sa.Enum('normal', 'large', native_enum=False), nullable=False))
    op.add_column('user_settings', sa.Column('layout_width', sa.Enum('normal', 'wide', native_enum=False), nullable=False))
    op.drop_column('user_settings', 'settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('user_settings', 'layout_width')
    op.drop_column('user_settings', 'font_size')
    op.drop_column('user_settings', 'theme_color')
    op.drop_column('user_settings', 'theme')
    # ### end Alembic commands ###
