"""comments reply to

Revision ID: 907b773ec0d1
Revises: d60fd0d42d46
Create Date: 2026-04-14 19:36:27.304881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907b773ec0d1'
down_revision: Union[str, Sequence[str], None] = 'd60fd0d42d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('comments', sa.Column('replied_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['replied_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'replied_to')
    op.drop_column('comments', 'is_deleted')
    # ### end Alembic commands ###
